### ISSUE TITLE
play in the game

### ISSUE THREAD

**Issue by wared2003** [IIM-Creative-Technology/for_how_much-service#4]
the main game activity, we have to create route for : get the question, 

When he is in room
- [x] chose chalenge
- [x] opponent chose number range 
- [x] 10s to chose number
- [x] revelea number 
if the numbers choose are different
- [x] reverse and divide by 2 the range

**Comment by romainmltr** [comment]
Fix the route

**Comment by romainmltr** [comment]
Check with Edouard
